# application.yml
aliyun:
  oss:
    endpoint: ${ALIYUN_NATION}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: firstbloglk
    url-prefix: ${ALIYUN_URL}


spring:
  data:
    redis:
      host: localhost
      port: 6379

  config:
    import: optional:file:.env[.properties]  # 这行是核心，告诉 Spring 去读 .env


  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}  # API 密钥
      base-url: https://api.deepseek.com  # API 地址（默认就是这个）
      model: deepseek-chat  # 模型名称

# 线程池配置
thread:
  pool:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60

#权限配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: App-Token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true