# application.yml
aliyun:
  oss:
    endpoint: ${ALIYUN_NATION}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: firstbloglk
    url-prefix: ${ALIYUN_URL}


spring:
  data:
    redis:
      host: localhost
      port: 6379

  config:
    import: optional:file:.env[.properties]  # 这行是核心，告诉 Spring 去读 .env

  mvc:
    async:
      request-timeout: 120000   #
# 线程池配置
thread:
  pool:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60

#权限配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: App-Token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

langchain4j:
  open-ai:
    chat-model:
      # 智谱 AI 的 OpenAI 兼容 API 地址
      base-url: https://open.bigmodel.cn/api/paas/v4
      # 你的智谱 API Key（替换成你自己的）
      api-key: ${ZHIPU_API_KEY}
      # 模型名称：GLM-5.1（你想用哪个就写哪个）
      model-name: GLM-4.7
      # 可选参数
      temperature: 0.4       # 0-2，越大回答越随机
      max-tokens: 512       # 最大输出 token 数
      top-p: 0.9             # 核采样参数
      log-requests: false    # 调试时可改为 true 看请求日志
      log-responses: false   # 调试时可改为 true 看响应日志

    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${ENABLE_MODLE_API_KEY}
      model-name: text-embedding-v3

    streaming-chat-model:
      base-url: https://open.bigmodel.cn/api/paas/v4   # 必须显式指定
      model-name:  GLM-4.6V
      api-key: ${ZHIPU_API_KEY}
      temperature: 0.4
      max-tokens: 3000
      top-p: 0.9
      log-requests: true
      log-responses: true
